@echo off
setlocal
cd /d "%~dp0"

set "CSC64=%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
set "CSC32=%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\csc.exe"
if exist "%CSC64%" set "CSC=%CSC64%"
if not exist "%CSC64%" set "CSC=%CSC32%"

if not exist "%CSC%" (
    echo [-] csc.exe not found - .NET Framework 4.x required.
    exit /b 1
)

echo [+] Compiler: %CSC%

for /f "delims=" %%i in ('powershell -NoProfile -Command "Get-Date -Format 'yyyy-MM-dd HH:mm:ss'"') do set "STAMP=%%i"

(
    echo // Auto-generated by compile.bat - do not edit.
    echo namespace DbgTool
    echo {
    echo     internal static class BuildInfo
    echo     {
    echo         internal const string BuildStamp = "%STAMP%";
    echo     }
    echo }
) > VersionInfo.cs

if not exist "..\..\build" mkdir "..\..\build"

"%CSC%" /nologo /codepage:65001 /target:exe /platform:anycpu ^
  /out:..\..\build\DbgTool.exe ^
  /r:System.dll /r:System.Core.dll ^
  Program.cs VersionInfo.cs Common\*.cs Core\*.cs

if errorlevel 1 (
    echo [-] Compile failed.
    exit /b 1
)

echo [+] OK: build\DbgTool.exe  (Build: %STAMP%)
exit /b 0
