#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Compile patched ACPI tables (src/acpi/patched/*.dsl) into C array hex files
(build/*.hex) that AcpiPatch.c #includes.

The patched .dsl sources are generated by tools/generate_patched_tables.py from
the original firmware tables; iASL recompiles them into legal AML (0 errors),
so the bootloader can swap the whole table via XSDT/FACP redirection without
touching firmware bytes at runtime.

Usage:
    python tools/build_patched_tables.py
"""

import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IASL = os.path.join(REPO, "tools", "isal", "iasl.exe")
BUILD = os.path.join(REPO, "build")

import generate_patched_tables

TABLES = [
    ("src/acpi/patched/ssdt4_patched.dsl", "ssdt4_patched"),
    ("src/acpi/patched/dsdt_patched.dsl", "dsdt_patched"),
]


def main():
    print("[*] Generating patched ACPI table DSLs...")
    generate_patched_tables.main()

    os.makedirs(BUILD, exist_ok=True)
    for src_rel, out_base in TABLES:
        src = os.path.join(REPO, src_rel)
        out = os.path.join(BUILD, out_base)

        r = subprocess.run([IASL, "-p", out, "-tc", src],
                           capture_output=True, text=True)
        combined = r.stdout + r.stderr
        for line in combined.splitlines():
            low = line.lower()
            if ("error" in low) or ("compilation successful" in low):
                print(line)

        if r.returncode != 0:
            print(f"[-] iASL failed for {src}")
            sys.exit(1)

        hex_path = out + ".hex"
        if not os.path.exists(hex_path):
            print(f"[-] Missing expected output: {hex_path}")
            sys.exit(1)

        print(f"[+] {hex_path}")

    print("[+] Patched ACPI tables built successfully.")


if __name__ == "__main__":
    main()
