import os
import glob

def table_id_to_uint64(table_id):
    # Pad to exactly 8 characters with spaces
    padded = table_id.ljust(8, ' ')[:8]
    val = 0
    for i, char in enumerate(padded):
        val |= ord(char) << (i * 8)
    return f"0x{val:016X}ULL"

def hex_to_c_array(hex_str):
    # Convert hex string to comma-separated hex bytes
    bytes_list = [f"0x{hex_str[i:i+2].upper()}" for i in range(0, len(hex_str), 2)]
    return ", ".join(bytes_list)

def main():
    patches_dir = r"E:\C\Custom_Bootloader\patches"
    output_header = r"E:\C\Custom_Bootloader\src\GeneratedPatches.h"
    
    patch_files = glob.glob(os.path.join(patches_dir, "*.txt"))
    
    header_content = []
    header_content.append("// Auto-generated by generate_patches.py. Do not edit.")
    header_content.append("#ifndef GENERATED_PATCHES_H")
    header_content.append("#define GENERATED_PATCHES_H")
    header_content.append("")
    header_content.append("#include \"UefiHelpers.h\"")
    header_content.append("")
    header_content.append("typedef struct {")
    header_content.append("    UINT64 OemTableId;")
    header_content.append("    const UINT8 *Search;")
    header_content.append("    UINTN SearchLen;")
    header_content.append("    const UINT8 *Replace;")
    header_content.append("    UINTN ReplaceLen;")
    header_content.append("    const CHAR16 *Name;")
    header_content.append("} ACPI_PATCH;")
    header_content.append("")

    patch_entries = []
    
    for patch_file in sorted(patch_files):
        name = os.path.splitext(os.path.basename(patch_file))[0]
        
        table = ""
        find_hex = ""
        replace_hex = ""
        
        with open(patch_file, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    k, v = line.split("=", 1)
                    k, v = k.strip().lower(), v.strip()
                    if k == "table":
                        table = v
                    elif k == "find":
                        find_hex = v
                    elif k == "replace":
                        replace_hex = v
                        
        if not table or not find_hex or not replace_hex:
            print(f"[-] Warning: Skipping invalid patch file: {patch_file}")
            continue
            
        oem_table_id = table_id_to_uint64(table)
        find_arr = hex_to_c_array(find_hex)
        replace_arr = hex_to_c_array(replace_hex)
        find_len = len(find_hex) // 2
        replace_len = len(replace_hex) // 2
        
        # Write static array declarations
        header_content.append(f"static const UINT8 Patch_{name}_Find[] = {{ {find_arr} }};")
        header_content.append(f"static const UINT8 Patch_{name}_Replace[] = {{ {replace_arr} }};")
        header_content.append("")
        
        # Convert name to wide string CHAR16 literal for EFI logging
        wide_name = "".join([f"L'{c}', " for c in name]) + "0"
        header_content.append(f"static const CHAR16 Patch_{name}_WName[] = {{ {wide_name} }};")
        header_content.append("")
        
        patch_entries.append(
            f"    {{ {oem_table_id}, Patch_{name}_Find, {find_len}, Patch_{name}_Replace, {replace_len}, Patch_{name}_WName }}"
        )
        
    header_content.append("static const ACPI_PATCH gPatches[] = {")
    header_content.append(",\n".join(patch_entries))
    header_content.append("};")
    header_content.append("")
    header_content.append(f"static const UINTN gPatchCount = {len(patch_entries)};")
    header_content.append("")
    header_content.append("#endif // GENERATED_PATCHES_H")
    
    with open(output_header, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(header_content) + "\n")
        
    print(f"[+] Successfully generated patches header: {output_header} ({len(patch_entries)} patches)")

if __name__ == "__main__":
    main()
