#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
在构建时生成版本工件。

每次构建（CMake 版本阶段运行本脚本）都会自动刷新：
  1. version.txt            - VERSION_BUILD=0x<YYYYMMDD>, VERSION_STRING=<major>.<YYYYMMDD>_<HHMMSS>
     （形如 "1.0.1" 的主版本前缀从上一次的 version.txt 保留）
  2. build/Version.h        - BUILD_VERSION / BUILD_VERSION_STR 宏（C）
  3. build/VersionData.asl  - SsdtUnlockDB GetVersion 使用的 Name (VERS, 0x...)

VERS 编码说明：WMI GetVersion 的返回值是 32 位 DWORD，装不下 BCD
YYYYMMDDHHMMSS（56 位）。因此 VERS 以 UTC Unix epoch 秒存储构建时间（可用到
2106 年）；DbgTool 将其解码为本地时间 "yyyy-MM-dd HH:mm:ss"。旧构建使用 BCD
日期 0x20YYMMDD（2020 年代构建的 epoch 值以 0x5E-0x6A 开头，因此两种编码可以
区分）。

Usage:
    python tools/generate_version.py [--out-dir DIR]

Version.h 与 VersionData.asl 固定输出到 build\（--out-dir 可覆盖）；version.txt
永远写仓库根目录（DbgTool 部署校验依赖它）。切勿再把它们生成到 src\ 下：
main.c 的 #include "Version.h" 会优先命中源文件同目录的 src/Version.h，
导致嵌入陈旧版本串（2026-09-21 实测踩过：二进制携带 28 分钟前的旧戳）。
"""

import argparse
import datetime
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VERSION_FILE = os.path.join(REPO, "version.txt")
DEFAULT_OUT_DIR = os.path.join(REPO, "build")


def main():
    parser = argparse.ArgumentParser(description="Generate version artifacts")
    parser.add_argument("--out-dir", default=DEFAULT_OUT_DIR,
                        help="output dir for Version.h / VersionData.asl "
                             "(default: <repo>/build)")
    args = parser.parse_args()

    out_dir = os.path.abspath(args.out_dir)
    output_header = os.path.join(out_dir, "Version.h")
    version_asl = os.path.join(out_dir, "VersionData.asl")

    now = datetime.datetime.now()
    date_str = now.strftime("%Y%m%d")
    time_str = now.strftime("%H%M%S")
    # 日期数字按十六进制解释：20260810 -> 0x20260810
    version_build = int(date_str, 16)
    # WMI GetVersion DWORD 取秒级精度：UTC Unix epoch 秒。
    version_epoch = int(now.astimezone(datetime.timezone.utc).timestamp())

    # 从上一次的 version.txt 保留主版本前缀（如 "1.0.1"）；每次构建只自动
    # 刷新日期后缀。兼容旧格式（1.0.3.20260905）与新格式（1.0.3_20260905.035425）。
    major = "1.0.0"
    if os.path.exists(VERSION_FILE):
        with open(VERSION_FILE, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line.startswith("VERSION_STRING="):
                    v = line.split("=", 1)[1].strip()
                    # 若存在则去掉尾部 _YYYYMMDD.HHMMSS（新格式）
                    if "_" in v:
                        v = v.split("_")[0]
                    parts = v.split(".")
                    if len(parts) >= 4 and parts[-1].isdigit() and len(parts[-1]) == 8:
                        major = ".".join(parts[:3])
                    else:
                        major = v.split("_")[0]
                    break

    version_str = "{}.{}_{}".format(major, date_str, time_str)

    # 1) 自动刷新 version.txt
    with open(VERSION_FILE, "w", encoding="utf-8", newline="\n") as f:
        f.write("VERSION_BUILD=0x{:08X}\n".format(version_build))
        f.write("VERSION_STRING={}\n".format(version_str))

    # 2) 生成 src/Version.h（C 宏）
    header = [
        "// Auto-generated by generate_version.py. Do not edit.",
        "#ifndef VERSION_H",
        "#define VERSION_H",
        "",
        "#define BUILD_VERSION 0x{:08X}ULL".format(version_build),
        '#define BUILD_VERSION_STR L"{}"'.format(version_str),
        "",
        "#endif // VERSION_H",
    ]
    os.makedirs(os.path.dirname(output_header), exist_ok=True)
    with open(output_header, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(header) + "\n")

    # 3) 生成 src/acpi/VersionData.asl（被 SsdtUnlockDB.asl include）。
    #    VERS = UTC Unix epoch 秒（见模块 docstring）；32 位 BCD 日期装不下
    #    一天中的时刻。
    asl = [
        "// Auto-generated by generate_version.py. Do not edit.",
        "// VERS = build time as UTC Unix epoch seconds (32-bit WMI DWORD",
        "// cannot hold BCD YYYYMMDDHHMMSS; DbgTool decodes this to local time).",
        "Name (VERS, 0x{:08X})".format(version_epoch),
    ]
    os.makedirs(os.path.dirname(version_asl), exist_ok=True)
    with open(version_asl, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(asl) + "\n")

    print("[+] version.txt updated: {} (0x{:08X})".format(version_str, version_build))
    print("[+] VERS (WMI epoch): 0x{:08X} ({})".format(version_epoch, version_epoch))
    print("[+] Generated: {}".format(output_header))
    print("[+] Generated: {}".format(version_asl))


if __name__ == "__main__":
    main()
