#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate version artifacts at build time.

Every build (build.bat runs this first) automatically refreshes:
  1. version.txt            - VERSION_BUILD=0x<YYYYMMDD>, VERSION_STRING=<major>.<YYYYMMDD>_<HHMMSS>
     (major prefix like "1.0.1" is preserved from the previous version.txt)
  2. src/Version.h          - BUILD_VERSION / BUILD_VERSION_STR macros (C)
  3. src/acpi/VersionData.asl - Name (VERS, 0x...) used by SsdtUnlockDB GetVersion

VERS encoding note: the WMI GetVersion return is a 32-bit DWORD, which cannot
hold BCD YYYYMMDDHHMMSS (56 bits). VERS therefore stores the build time as
UTC Unix epoch seconds (fits until 2106); DbgTool decodes it to local
"yyyy-MM-dd HH:mm:ss". Legacy builds used BCD date 0x20YYMMDD (epoch values of
2020s builds start 0x5E-0x6A, so the two encodings are distinguishable).

Usage:
    python tools/generate_version.py
"""

import datetime
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VERSION_FILE = os.path.join(REPO, "version.txt")
OUTPUT_HEADER = os.path.join(REPO, "src", "Version.h")
VERSION_ASL = os.path.join(REPO, "src", "acpi", "VersionData.asl")


def main():
    now = datetime.datetime.now()
    date_str = now.strftime("%Y%m%d")
    time_str = now.strftime("%H%M%S")
    # Date digits interpreted as hex: 20260810 -> 0x20260810
    version_build = int(date_str, 16)
    # Second precision for the WMI GetVersion DWORD: UTC Unix epoch seconds.
    version_epoch = int(now.astimezone(datetime.timezone.utc).timestamp())

    # Preserve the major version prefix (e.g. "1.0.1") from the previous
    # version.txt; only the date suffix is auto-refreshed each build.
    # Handles both old format (1.0.3.20260905) and new format (1.0.3_20260905.035425).
    major = "1.0.0"
    if os.path.exists(VERSION_FILE):
        with open(VERSION_FILE, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line.startswith("VERSION_STRING="):
                    v = line.split("=", 1)[1].strip()
                    # Strip trailing _YYYYMMDD.HHMMSS if present (new format)
                    if "_" in v:
                        v = v.split("_")[0]
                    parts = v.split(".")
                    if len(parts) >= 4 and parts[-1].isdigit() and len(parts[-1]) == 8:
                        major = ".".join(parts[:3])
                    else:
                        major = v.split("_")[0]
                    break

    version_str = "{}.{}_{}".format(major, date_str, time_str)

    # 1) Auto-refresh version.txt
    with open(VERSION_FILE, "w", encoding="utf-8", newline="\n") as f:
        f.write("VERSION_BUILD=0x{:08X}\n".format(version_build))
        f.write("VERSION_STRING={}\n".format(version_str))

    # 2) Generate src/Version.h (C macros)
    header = [
        "// Auto-generated by generate_version.py. Do not edit.",
        "#ifndef VERSION_H",
        "#define VERSION_H",
        "",
        "#define BUILD_VERSION 0x{:08X}ULL".format(version_build),
        '#define BUILD_VERSION_STR L"{}"'.format(version_str),
        "",
        "#endif // VERSION_H",
    ]
    os.makedirs(os.path.dirname(OUTPUT_HEADER), exist_ok=True)
    with open(OUTPUT_HEADER, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(header) + "\n")

    # 3) Generate src/acpi/VersionData.asl (included by SsdtUnlockDB.asl).
    #    VERS = UTC Unix epoch seconds (see module docstring); a 32-bit BCD
    #    date cannot carry the time of day.
    asl = [
        "// Auto-generated by generate_version.py. Do not edit.",
        "// VERS = build time as UTC Unix epoch seconds (32-bit WMI DWORD",
        "// cannot hold BCD YYYYMMDDHHMMSS; DbgTool decodes this to local time).",
        "Name (VERS, 0x{:08X})".format(version_epoch),
    ]
    os.makedirs(os.path.dirname(VERSION_ASL), exist_ok=True)
    with open(VERSION_ASL, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(asl) + "\n")

    print("[+] version.txt updated: {} (0x{:08X})".format(version_str, version_build))
    print("[+] VERS (WMI epoch): 0x{:08X} ({})".format(version_epoch, version_epoch))
    print("[+] Generated: {}".format(OUTPUT_HEADER))
    print("[+] Generated: {}".format(VERSION_ASL))


if __name__ == "__main__":
    main()
