// Auto-generated by generate_patches.py. Do not edit.
#ifndef GENERATED_PATCHES_H
#define GENERATED_PATCHES_H

#include "UefiHelpers.h"

typedef struct {
    UINT64 OemTableId;
    const UINT8 *Search;
    UINTN SearchLen;
    const UINT8 *Replace;
    UINTN ReplaceLen;
    const CHAR16 *Name;
} ACPI_PATCH;

static const UINT8 Patch_atp2_unlock_Find[] = { 0x70, 0x0B, 0x68, 0x01, 0x41, 0x54, 0x50, 0x32 };
static const UINT8 Patch_atp2_unlock_Replace[] = { 0x70, 0x0B, 0xE0, 0x01, 0x41, 0x54, 0x50, 0x32 };

static const CHAR16 Patch_atp2_unlock_WName[] = { L'a', L't', L'p', L'2', L'_', L'u', L'n', L'l', L'o', L'c', L'k', 0 };

static const UINT8 Patch_atpp_unlock_Find[] = { 0x70, 0x0B, 0x68, 0x01, 0x41, 0x54, 0x50, 0x50 };
static const UINT8 Patch_atpp_unlock_Replace[] = { 0x70, 0x0B, 0xE0, 0x01, 0x41, 0x54, 0x50, 0x50 };

static const CHAR16 Patch_atpp_unlock_WName[] = { L'a', L't', L'p', L'p', L'_', L'u', L'n', L'l', L'o', L'c', L'k', 0 };

static const UINT8 Patch_nce2_unlock_Find[] = { 0x70, 0x01, 0x4E, 0x43, 0x45, 0x32 };
static const UINT8 Patch_nce2_unlock_Replace[] = { 0x70, 0x00, 0x4E, 0x43, 0x45, 0x32 };

static const CHAR16 Patch_nce2_unlock_WName[] = { L'n', L'c', L'e', L'2', L'_', L'u', L'n', L'l', L'o', L'c', L'k', 0 };

static const ACPI_PATCH gPatches[] = {
    { 0x20202020324B4445ULL, Patch_atp2_unlock_Find, 8, Patch_atp2_unlock_Replace, 8, Patch_atp2_unlock_WName },
    { 0x20202020324B4445ULL, Patch_atpp_unlock_Find, 8, Patch_atpp_unlock_Replace, 8, Patch_atpp_unlock_WName },
    { 0x20202020324B4445ULL, Patch_nce2_unlock_Find, 6, Patch_nce2_unlock_Replace, 6, Patch_nce2_unlock_WName }
};

static const UINTN gPatchCount = 3;

#endif // GENERATED_PATCHES_H
